const data = [
    {
        "employer_company_type": "Information",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
        "employer_name": "Dice",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-dice-3634229135",
        "job_apply_quality_score": 0.5631,
        "job_benefits": null,
        "job_city": "Bentonville",
        "job_country": "US",
        "job_description": "Dice is the leading career destination for tech experts at every stage of their careers. Our client, WB Solutions LLC, is seeking the following. Apply via Dice today! Greetings from WB SOLUTIONS !!!! We had a urgent requirement for REACT DEVELOPER at BENTONVILLE, AR (NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) ROLE: REACT DEVELOPER LOCATION: BENTONVILLE, AR (NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) Skills: React.Js, React Native, REDUX, JavaScript, RETAIL DOMAIN EXP",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ig4EYbxS7NIAAAAAAAAAAA%3D%3D",
        "job_highlights": {},
        "job_id": "ig4EYbxS7NIAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_naics_code": "519130",
        "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals",
        "job_offer_expiration_datetime_utc": "2023-07-12T15:00:22.000Z",
        "job_offer_expiration_timestamp": 1689174022,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-12T15:00:22.000Z",
        "job_posted_at_timestamp": 1686582022,
        "job_posting_language": "en",
        "job_publisher": "LinkedIn",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": false,
        },
        "job_required_experience": {
            "experience_mentioned": false,
            "experience_preferred": false,
            "no_experience_required": false,
            "required_experience_in_months": null,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": "AR",
        "job_title": "React developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": null,
        "employer_name": "Curbio",
        "employer_website": "http://curbio.com",
        "job_apply_is_direct": false,
        "job_apply_link": "https://jobs.jobvite.com/curbio/job/o9kynfw8",
        "job_apply_quality_score": 0.7571,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Looking to join an innovative and high growth company run by a recognized and successful team of co-founders and executives? Well, it’s an exciting time to join Curbio, a Real Estate Tech company founded in 2017 to transform the multi-billion dollar home improvement and residential real estate market. We help real estate agents and their clients get listings ready for market with smart home improvements and a fix now, pay later model. We are using technology to completely re-invent the archaic home improvement experience and make it work for real estate. Curbio fosters a creative and supportive work environment that encourages our staff to reach and surpass their full potential. We believe that unity of goals and diversity of people is a powerful combination. We believe that personal responsibility almost always outperforms corporate policies. Our team is focused, driven and inventive. Curbio has been recognized for exemplary leadership and company culture many times over. In 2022, Curbio made both Inc.’s Top 5000 fastest growing companies in America as well as Deloitte’s Technology Fast 500. We are certified as a Great Place to Work® and our CEO, Rick Rudman, was named a 2021 & 2022 Best CEO by Comparably, where we also received distinctions for Happiest Employees and Best Compensation. Curbio has also been recognized for its success as a tech-powered home improvement solution, receiving nods in the Qualified Remodeler Top 500 list, PropTech Breakthrough awards, Best in Biz awards and NTVC Tech 100 awards, to name a few. We won’t bore you with our amazing benefits (they are, we got an award on those too). But if you want to work with an experienced management team that wants to create a great workplace environment, present new opportunities and challenges, provide a clear path for career growth, and work in a collaborative environment with dedicated people - this is the place for you. Join Curbio today and help us make real estate move! At Curbio you will: • Serve as a frontend software developer specializing primarily in React Native, but with React web experience as well. • Report directly to the CTO. • Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties. • Pay attention to detail and refactor as you go. • Meet with the development team to discuss user interface ideas and applications. • Review application requirements and interface designs. • Refine the CI/CD pipeline and Cloud Ops processes. What we’re looking for: • 5+ years of experience working with React and React Native. • Experience working in .Net Framework or .Net Core is a plus. • Front End: React & Material Design. • Back End: C# .Net Core, SQL Server. • Infrastructure: Azure & Azure Functions. • A firm commitment to quality code. • Experience working as a developer in an agile process with a regular sprint schedule, user stories prioritized from a backlog and sprint reviews, preferred. • Native development experience in Swift or Objective-C for iOS, or Java for Android, a plus.        Curbio is proud to be an Equal Opportunity Employer. As such, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity, Veteran status or any other characteristic protected under federal, state, or applicable local law",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=QwuiV6NotOkAAAAAAAAAAA%3D%3D",
        "job_highlights": {
            "Qualifications": [
                "5+ years of experience working with React and React Native",
                "Front End: React & Material Design",
                "Back End: C# .Net Core, SQL Server",
                "Infrastructure: Azure & Azure Functions",
                "A firm commitment to quality code",
            ],
            "Responsibilities": [
                "Report directly to the CTO",
                "Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties",
                "Pay attention to detail and refactor as you go",
                "Meet with the development team to discuss user interface ideas and applications",
                "Review application requirements and interface designs",
                "Refine the CI/CD pipeline and Cloud Ops processes",
            ],
        },
        "job_id": "QwuiV6NotOkAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-08T00:00:00.000Z",
        "job_posted_at_timestamp": 1686182400,
        "job_posting_language": "en",
        "job_publisher": "Jobvite",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": true,
        },
        "job_required_experience": {
            "experience_mentioned": true,
            "experience_preferred": true,
            "no_experience_required": false,
            "required_experience_in_months": 60,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": null,
        "job_title": "React Developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLnyiUSadBRlx11LXARvrGOe_Yzn-Ye1qi6SQA&s=0",
        "employer_name": "Mobomo",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/senior-react-developer-at-mobomo-3634891130",
        "job_apply_quality_score": 0.5741,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Responsibilities • Work with project team members to deliver technical solutions that meet the needs of our customers. • Architect, build and maintain React Native apps and React-based dashboards. • Connect data sources, analyze data, build business logic, and configure visualizations. • Apply Agile principles to gather business requirements and translate them into functional/technical specifications. • Build reusable code and libraries for future use. • Develop and optimize applications for maximum speed and scalability. • Create and maintain technical and knowledge base documentation. • Diagnose pro...(truncated to the first 10000 characters)"
    },
    {
        "employer_company_type": "Information",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
        "employer_name": "Dice",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-dice-3634229135",
        "job_apply_quality_score": 0.5631,
        "job_benefits": null,
        "job_city": "Bentonville",
        "job_country": "US",
        "job_description": "Dice is the leading career destination for tech experts at every stage of their careers. Our client, WB Solutions LLC, is seeking the following. Apply via Dice today! Greetings from WB SOLUTIONS !!!! We had a urgent requirement for REACT DEVELOPER at BENTONVILLE, AR(NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) ROLE: REACT DEVELOPER LOCATION: BENTONVILLE, AR(NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) Skills: React.Js, React Native, REDUX, JavaScript, RETAIL DOMAIN EXP",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ig4EYbxS7NIAAAAAAAAAAA%3D%3D",
        "job_highlights": {},
        "job_id": "ig4EYbxS7NIAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_naics_code": "519130",
        "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals",
        "job_offer_expiration_datetime_utc": "2023-07-12T15:00:22.000Z",
        "job_offer_expiration_timestamp": 1689174022,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-12T15:00:22.000Z",
        "job_posted_at_timestamp": 1686582022,
        "job_posting_language": "en",
        "job_publisher": "LinkedIn",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": false,
        },
        "job_required_experience": {
            "experience_mentioned": false,
            "experience_preferred": false,
            "no_experience_required": false,
            "required_experience_in_months": null,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": "AR",
        "job_title": "React developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": null,
        "employer_name": "Curbio",
        "employer_website": "http://curbio.com",
        "job_apply_is_direct": false,
        "job_apply_link": "https://jobs.jobvite.com/curbio/job/o9kynfw8",
        "job_apply_quality_score": 0.7571,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Looking to join an innovative and high growth company run by a recognized and successful team of co-founders and executives? Well, it’s an exciting time to join Curbio, a Real Estate Tech company founded in 2017 to transform the multi-billion dollar home improvement and residential real estate market. We help real estate agents and their clients get listings ready for market with smart home improvements and a fix now, pay later model. We are using technology to completely re-invent the archaic home improvement experience and make it work for real estate. Curbio fosters a creative and supportive work environment that encourages our staff to reach and surpass their full potential.We believe that unity of goals and diversity of people is a powerful combination.We believe that personal responsibility almost always outperforms corporate policies.Our team is focused, driven and inventive. Curbio has been recognized for exemplary leadership and company culture many times over.In 2022, Curbio made both Inc.’s Top 5000 fastest growing companies in America as well as Deloitte’s Technology Fast 500. We are certified as a Great Place to Work® and our CEO, Rick Rudman, was named a 2021 & 2022 Best CEO by Comparably, where we also received distinctions for Happiest Employees and Best Compensation.Curbio has also been recognized for its success as a tech - powered home improvement solution, receiving nods in the Qualified Remodeler Top 500 list, PropTech Breakthrough awards, Best in Biz awards and NTVC Tech 100 awards, to name a few. We won’t bore you with our amazing benefits(they are, we got an award on those too).But if you want to work with an experienced management team that wants to create a great workplace environment, present new opportunities and challenges, provide a clear path for career growth, and work in a collaborative environment with dedicated people - this is the place for you. Join Curbio today and help us make real estate move! At Curbio you will: • Serve as a frontend software developer specializing primarily in React Native, but with React web experience as well. • Report directly to the CTO. • Communicate – understand when it’s a technical decision vs.a product decision and socialize uncertainties  • Pay attention to detail and refactor as you go. • Meet with the development team to discuss user interface ideas and applications. • Review application requirements and interface designs. • Refine the CI / CD pipeline and Cloud Ops processes. What we’re looking for: • 5 + years of experience working with React and React Native. • Experience working in .Net Framework or.Net Core is a plus. • Front End: React & Material Design. • Back End: C#.Net Core, SQL Server. • Infrastructure: Azure & Azure Functions. • A firm commitment to quality code. • Experience working as a developer in an agile process with a regular sprint schedule, user stories prioritized from a backlog and sprint reviews, preferred. • Native development experience in Swift or Objective - C for iOS, or Java for Android, a plus.        Curbio is proud to be an Equal Opportunity Employer.As such, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity, Veteran status or any other characteristic protected under federal, state, or applicable local law",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=QwuiV6NotOkAAAAAAAAAAA%3D%3D",
        "job_highlights": {
            "Qualifications": [
                "5+ years of experience working with React and React Native",
                "Front End: React & Material Design",
                "Back End: C# .Net Core, SQL Server",
                "Infrastructure: Azure & Azure Functions",
                "A firm commitment to quality code",
            ],
            "Responsibilities": [
                "Report directly to the CTO",
                "Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties",
                "Pay attention to detail and refactor as you go",
                "Meet with the development team to discuss user interface ideas and applications",
                "Review application requirements and interface designs",
                "Refine the CI/CD pipeline and Cloud Ops processes",
            ],
        },
        "job_id": "QwuiV6NotOkAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-08T00:00:00.000Z",
        "job_posted_at_timestamp": 1686182400,
        "job_posting_language": "en",
        "job_publisher": "Jobvite",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": true,
        },
        "job_required_experience": {
            "experience_mentioned": true,
            "experience_preferred": true,
            "no_experience_required": false,
            "required_experience_in_months": 60,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": null,
        "job_title": "React Developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLnyiUSadBRlx11LXARvrGOe_Yzn-Ye1qi6SQA&s=0",
        "employer_name": "Mobomo",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/senior-react-developer-at-mobomo-3634891130",
        "job_apply_quality_score": 0.5741,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Responsibilities • Work with project team members to deliver technical solutions that meet the needs of our customers. • Architect, build and maintain React Native apps and React - based dashboards. • Connect data sources, analyze data, build business logic, and configure visualizations. • Apply Agile principles to gather business requirements and translate them into functional / technical specifications. • Build reusable code and libraries for future use. • Develop and optimize applications for maximum speed and scalability. • Create and maintain technical and knowledge base documentation. • Diagnose pro...(truncated to the first 10000 characters)"
    },
    {
        "employer_company_type": "Information",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
        "employer_name": "Dice",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-dice-3634229135",
        "job_apply_quality_score": 0.5631,
        "job_benefits": null,
        "job_city": "Bentonville",
        "job_country": "US",
        "job_description": "Dice is the leading career destination for tech experts at every stage of their careers. Our client, WB Solutions LLC, is seeking the following. Apply via Dice today! Greetings from WB SOLUTIONS!!!!  We had a urgent requirement for REACT DEVELOPER at BENTONVILLE, AR(NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) ROLE: REACT DEVELOPER LOCATION: BENTONVILLE, AR(NEED TO BE LOCAL AND HYBRID BASIS DAY ONE ONSITE) Skills: React.Js, React Native, REDUX, JavaScript, RETAIL DOMAIN EXP",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ig4EYbxS7NIAAAAAAAAAAA%3D%3D",
        "job_highlights": {},
        "job_id": "ig4EYbxS7NIAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_naics_code": "519130",
        "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals",
        "job_offer_expiration_datetime_utc": "2023-07-12T15:00:22.000Z",
        "job_offer_expiration_timestamp": 1689174022,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-12T15:00:22.000Z",
        "job_posted_at_timestamp": 1686582022,
        "job_posting_language": "en",
        "job_publisher": "LinkedIn",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": false,
        },
        "job_required_experience": {
            "experience_mentioned": false,
            "experience_preferred": false,
            "no_experience_required": false,
            "required_experience_in_months": null,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": "AR",
        "job_title": "React developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": null,
        "employer_name": "Curbio",
        "employer_website": "http://curbio.com",
        "job_apply_is_direct": false,
        "job_apply_link": "https://jobs.jobvite.com/curbio/job/o9kynfw8",
        "job_apply_quality_score": 0.7571,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Looking to join an innovative and high growth company run by a recognized and successful team of co-founders and executives? Well, it’s an exciting time to join Curbio, a Real Estate Tech company founded in 2017 to transform the multi-billion dollar home improvement and residential real estate market. We help real estate agents and their clients get listings ready for market with smart home improvements and a fix now, pay later model. We are using technology to completely re-invent the archaic home improvement experience and make it work for real estate. Curbio fosters a creative and supportive work environment that encourages our staff to reach and surpass their full potential.We believe that unity of goals and diversity of people is a powerful combination.We believe that personal responsibility almost always outperforms corporate policies.Our team is focused, driven and inventive. Curbio has been recognized for exemplary leadership and company culture many times over.In 2022, Curbio made both Inc.’s Top 5000 fastest growing companies in America as well as Deloitte’s Technology Fast 500. We are certified as a Great Place to Work® and our CEO, Rick Rudman, was named a 2021 & 2022 Best CEO by Comparably, where we also received distinctions for Happiest Employees and Best Compensation.Curbio has also been recognized for its success as a tech - powered home improvement solution, receiving nods in the Qualified Remodeler Top 500 list, PropTech Breakthrough awards, Best in Biz awards and NTVC Tech 100 awards, to name a few. We won’t bore you with our amazing benefits(they are, we got an award on those too).But if you want to work with an experienced management team that wants to create a great workplace environment, present new opportunities and challenges, provide a clear path for career growth, and work in a collaborative environment with dedicated people - this is the place for you. Join Curbio today and help us make real estate move! At Curbio you will: • Serve as a frontend software developer specializing primarily in React Native, but with React web experience as well. • Report directly to the CTO. • Communicate – understand when it’s a technical decision vs.a product decision and socialize uncertainties. • Pay attention to detail and refactor as you go. • Meet with the development team to discuss user interface ideas and applications. • Review application requirements and interface designs. • Refine the CI / CD pipeline and Cloud Ops processes. What we’re looking for: • 5 + years of experience working with React and React Native. • Experience working in .Net Framework or.Net Core is a plus. • Front End: React & Material Design. • Back End: C#.Net Core, SQL Server. • Infrastructure: Azure & Azure Functions. • A firm commitment to quality code. • Experience working as a developer in an agile process with a regular sprint schedule, user stories prioritized from a backlog and sprint reviews, preferred. • Native development experience in Swift or Objective - C for iOS, or Java for Android, a plus.        Curbio is proud to be an Equal Opportunity Employer.As such, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity, Veteran status or any other characteristic protected under federal, state, or applicable local law",
        "job_employment_type": "FULLTIME",
        "job_experience_in_place_of_education": false,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=QwuiV6NotOkAAAAAAAAAAA%3D%3D",
        "job_highlights": {
            "Qualifications": [
                "5+ years of experience working with React and React Native",
                "Front End: React & Material Design",
                "Back End: C# .Net Core, SQL Server",
                "Infrastructure: Azure & Azure Functions",
                "A firm commitment to quality code",
            ],
            "Responsibilities": [
                "Report directly to the CTO",
                "Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties",
                "Pay attention to detail and refactor as you go",
                "Meet with the development team to discuss user interface ideas and applications",
                "Review application requirements and interface designs",
                "Refine the CI/CD pipeline and Cloud Ops processes",
            ],
        },
        "job_id": "QwuiV6NotOkAAAAAAAAAAA==",
        "job_is_remote": false,
        "job_job_title": null,
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_max_salary": null,
        "job_min_salary": null,
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_onet_job_zone": "3",
        "job_onet_soc": "15113400",
        "job_posted_at_datetime_utc": "2023-06-08T00:00:00.000Z",
        "job_posted_at_timestamp": 1686182400,
        "job_posting_language": "en",
        "job_publisher": "Jobvite",
        "job_required_education": {
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "high_school": false,
            "postgraduate_degree": false,
            "professional_certification": false,
            "professional_certification_mentioned": true,
        },
        "job_required_experience": {
            "experience_mentioned": true,
            "experience_preferred": true,
            "no_experience_required": false,
            "required_experience_in_months": 60,
        },
        "job_required_skills": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_state": null,
        "job_title": "React Developer",
    },
    {
        "employer_company_type": null,
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLnyiUSadBRlx11LXARvrGOe_Yzn-Ye1qi6SQA&s=0",
        "employer_name": "Mobomo",
        "employer_website": null,
        "job_apply_is_direct": false,
        "job_apply_link": "https://www.linkedin.com/jobs/view/senior-react-developer-at-mobomo-3634891130",
        "job_apply_quality_score": 0.5741,
        "job_benefits": null,
        "job_city": null,
        "job_country": "US",
        "job_description": "Responsibilities • Work with project team members to deliver technical solutions that meet the needs of our customers. • Architect, build and maintain React Native apps and React - based dashboards. • Connect data sources, analyze data, build business logic, and configure visualizations. • Apply Agile principles to gather business requirements and translate them into functional / technical specifications. • Build reusable code and libraries for future use. • Develop and optimize applications for maximum speed and scalability. • Create and maintain technical and knowledge base documentation. • Diagnose pro...(truncated to the first 10000 characters)"
    }
]

export default data
